language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn install

script:
  - yarn test

after_script:
  - yarn codecov && yarn coveralls
